spring.application.name=api-gateway
server.port=${PORT:8080}

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

sri.gateway.auth-service-url=${AUTH_SERVICE_URL:http://localhost:8081}
sri.gateway.cultivos-service-url=${CULTIVOS_SERVICE_URL:http://localhost:8082}
sri.gateway.sensores-service-url=${SENSORES_SERVICE_URL:http://localhost:8083}
sri.gateway.riego-service-url=${RIEGO_SERVICE_URL:http://localhost:8084}
sri.gateway.reportes-service-url=${REPORTES_SERVICE_URL:http://localhost:8085}
sri.gateway.chat-service-url=${CHAT_SERVICE_URL:http://localhost:8086}
