spring.application.name=riego-service
server.port=${PORT:8084}

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://switchyard.proxy.rlwy.net:10870/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mPKqzsHFJXyydnCcsxhyjXrjovGianqU}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

sri.services.sensores-url=${SENSORES_SERVICE_URL:http://localhost:8083}
