spring.application.name=riego-service
server.port=${PORT:8084}

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USER}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

sri.services.sensores-url=${SENSORES_SERVICE_URL:http://localhost:8083}
