spring.application.name=chat-service
server.port=${PORT:8086}

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.ai.openai.base-url=${SPRING_AI_OPENAI_BASE_URL:https://models.github.ai/inference}
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=${SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL:openai/gpt-4o-mini}
